[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'cd client && npm install',
  'cd client && npm run build',
  'cd .. && npm prune --omit=dev'
]

[start]
cmd = 'node server/index.js'
